/*---------------------------------------------------------------------------------------------
 * Copyright (c) Bentley Systems, Incorporated. All rights reserved.
 * See LICENSE.md in the project root for license terms and full copyright notice.
 *--------------------------------------------------------------------------------------------*/
/** @packageDocumentation
 * @module iModels
 */

import {
  DefinitionModel,
  // eslint-disable-next-line @typescript-eslint/no-redeclare
  Element,
  ElementAspect,
  ElementMultiAspect,
  ElementRefersToElements,
  ElementUniqueAspect,
  GeometricElement,
  IModelDb,
  Model,
  RecipeDefinitionElement,
  Relationship,
} from "@itwin/core-backend";
import {
  assert,
  Id64String,
  IModelStatus,
  ITwinError,
  Logger,
  YieldManager,
} from "@itwin/core-bentley";
import {
  ChangesetFileProps,
  CodeSpec,
  FontFamilyDescriptor,
  FontId,
  FontProps,
  IModel,
  IModelError,
  QueryBinder,
} from "@itwin/core-common";
import { ECVersion, Schema, SchemaKey } from "@itwin/ecschema-metadata";
import { TransformerLoggerCategory } from "./TransformerLoggerCategory";
import * as nodeAssert from "assert";
import { ElementAspectExportProcessor } from "./ElementAspectExportProcessor";
import {
  ElementAspectExportCoordinator,
  registerElementAspectExportCoordinator,
} from "./ElementAspectExportCoordinator";
import {
  ChangedInstanceIds,
  type ChangedInstanceIdsInitOptions,
  ChangedInstanceOps,
  getAspectOwnerElementIds,
} from "./ChangedInstanceIds";
export {
  ChangedInstanceIds,
  type ChangedInstanceIdsInitOptions,
  ChangedInstanceOps,
};

const loggerCategory = TransformerLoggerCategory.IModelExporter;

/**
 * @beta
 * The (optional) result of [[IModelExportHandler.onExportSchema]]
 */
export interface ExportSchemaResult {
  /** set this property to notify subclasses where you wrote a schema for later import */
  schemaPath?: string;
}

/**
 * Arguments for [[IModelExporter.initialize]], usually in case you want to query changedata early
 * such as in the case of the IModelTransformer
 * @beta
 */
export type ExporterInitOptions = ExportChangesOptions;

/**
 * Arguments for [[IModelExporter.exportChanges]]
 * @public
 */
export type ExportChangesOptions = {
  skipPropagateChangesToRootElements?: boolean;
} /**
 * an array of ChangesetFileProps which are used to read the changesets and populate the ChangedInstanceIds using [[ChangedInstanceIds.initialize]] in [[IModelExporter.exportChanges]]
 * @note mutually exclusive with @see changesetRanges, @see startChangeset and @see changedInstanceIds, so define one of the four, never more
 */ & (
  | { csFileProps: ChangesetFileProps[] }
  /**
   * Class instance that contains modified elements between 2 versions of an iModel.
   * If this parameter is not provided, then [[ChangedInstanceIds.initialize]] in [[IModelExporter.exportChanges]]
   * will be called to discover changed elements.
   * @note mutually exclusive with @see changesetRanges, @see csFileProps and @see startChangeset, so define one of the four, never more
   */
  | { changedInstanceIds: ChangedInstanceIds }
  /**
   * An ordered array of changeset index ranges, e.g. [[2,2], [4,5]] is [2,4,5]
   * @note mutually exclusive with @see changedInstanceIds, @see csFileProps and @see startChangeset, so define one of the four, never more
   */
  | { changesetRanges: [number, number][] }
  /**
   * Include changes from this changeset up through and including the current changeset.
   * @note To form a range of versions to process, set `startChangeset` for the start (inclusive)
   * of the desired range and open the source iModel as of the end (inclusive) of the desired range.
   * @default the current changeset of the sourceDb, if undefined
   */
  | { startChangeset: { id?: string; index?: number } }
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  | {}
);

/** Handles the events generated by IModelExporter.
 * @note Change information is available when `IModelExportHandler` methods are invoked via [IModelExporter.exportChanges]($transformer), but not available when invoked via [IModelExporter.exportAll]($transformer).
 * @note The handler is intended to be owned by (registered with) and called from the IModelExporter exclusively
 * @see [iModel Transformation and Data Exchange]($docs/learning/transformer/index.md), [IModelExporter]($transformer)
 * @beta
 */
export abstract class IModelExportHandler {
  /** If `true` is returned, then the CodeSpec will be exported.
   * @note This method can optionally be overridden to exclude an individual CodeSpec from the export. The base implementation always returns `true`.
   */
  public async shouldExportCodeSpec(_codeSpec: CodeSpec): Promise<boolean> {
    return true;
  }

  /** Called when a CodeSpec should be exported.
   * @param codeSpec The CodeSpec to export
   * @param isUpdate If defined, then `true` indicates an UPDATE operation while `false` indicates an INSERT operation. If not defined, then INSERT vs. UPDATE is not known.
   * @note This should be overridden to actually do the export.
   */
  public async onExportCodeSpec(
    _codeSpec: CodeSpec,
    _isUpdate: boolean | undefined
  ): Promise<void> {}

  /** Called when a font should be exported.
   * @param font The font to export
   * @param isUpdate If defined, then `true` indicates an UPDATE operation while `false` indicates an INSERT operation. If not defined, then INSERT vs. UPDATE is not known.
   * @note This should be overridden to actually do the export.
   */
  public async onExportFont(
    _font: FontProps,
    _isUpdate: boolean | undefined
  ): Promise<void> {}

  /** Called when a model should be exported.
   * @param model The model to export
   * @param isUpdate If defined, then `true` indicates an UPDATE operation while `false` indicates an INSERT operation. If not defined, then INSERT vs. UPDATE is not known.
   * @note This should be overridden to actually do the export.
   */
  public async onExportModel(
    _model: Model,
    _isUpdate: boolean | undefined
  ): Promise<void> {}

  /** Called when a model should be deleted. */
  public async onDeleteModel(_modelId: Id64String): Promise<void> {}

  /** If `true` is returned, then the element will be exported.
   * @note This method can optionally be overridden to exclude an individual Element (and its children and ElementAspects) from the export. The base implementation always returns `true`.
   */
  public async shouldExportElement(_element: Element): Promise<boolean> {
    return true;
  }

  /** Called when element is skipped instead of exported.
   * @note When an element is skipped, exporter will not export any of its child elements. Because of this, [[onSkipElement]] will not be invoked for any children of a "skipped" element.
   */
  public async onSkipElement(_elementId: Id64String): Promise<void> {}

  /** Called when an element should be exported.
   * @param element The element to export
   * @param isUpdate If defined, then `true` indicates an UPDATE operation while `false` indicates an INSERT operation. If not defined, then INSERT vs. UPDATE is not known.
   * @note This should be overridden to actually do the export.
   */
  public async onExportElement(
    _element: Element,
    _isUpdate: boolean | undefined
  ): Promise<void> {}

  /**
   * Do any asynchronous actions before exporting an element
   * @note Do not implement this handler manually, it is internal, it will be removed.
   *       This will become a part of onExportElement once that becomes async
   * @internal
   */
  public async preExportElement(_element: Element): Promise<void> {}

  /** Called when an element should be deleted. */
  public async onDeleteElement(_elementId: Id64String): Promise<void> {}

  /** If `true` is returned, then the ElementAspect will be exported.
   * @note This method can optionally be overridden to exclude an individual ElementAspect from the export. The base implementation always returns `true`.
   */
  public async shouldExportElementAspect(
    _aspect: ElementAspect
  ): Promise<boolean> {
    return true;
  }

  /** Called when an ElementUniqueAspect should be exported.
   * @param aspect The ElementUniqueAspect to export
   * @param isUpdate If defined, then `true` indicates an UPDATE operation while `false` indicates an INSERT operation. If not defined, then INSERT vs. UPDATE is not known.
   * @note This should be overridden to actually do the export.
   */
  public async onExportElementUniqueAspect(
    _aspect: ElementUniqueAspect,
    _isUpdate: boolean | undefined
  ): Promise<void> {}

  /** Called when ElementMultiAspects should be exported.
   * @note This should be overridden to actually do the export.
   */
  public async onExportElementMultiAspects(
    _aspects: ElementMultiAspect[]
  ): Promise<void> {}

  /** If `true` is returned, then the relationship will be exported.
   * @note This method can optionally be overridden to exclude an individual CodeSpec from the export. The base implementation always returns `true`.
   */
  public async shouldExportRelationship(
    _relationship: Relationship
  ): Promise<boolean> {
    return true;
  }

  /** Called when a Relationship should be exported.
   * @param relationship The Relationship to export
   * @param isUpdate If defined, then `true` indicates an UPDATE operation while `false` indicates an INSERT operation. If not defined, then INSERT vs. UPDATE is not known.
   * @note This should be overridden to actually do the export.
   */
  public async onExportRelationship(
    _relationship: Relationship,
    _isUpdate: boolean | undefined
  ): Promise<void> {}

  /** Called when a relationship should be deleted. */
  public async onDeleteRelationship(
    _relInstanceId: Id64String
  ): Promise<void> {}

  /** If `true` is returned, then the schema will be exported.
   * @note This method can optionally be overridden to exclude an individual schema from the export. The base implementation always returns `true`.
   */
  public async shouldExportSchema(_schemaKey: SchemaKey): Promise<boolean> {
    return true;
  }

  /** Called when a schema should be exported.
   * @param schema The schema to export
   * @note This should be overridden to actually do the export.
   * @note return an [[ExportSchemaResult]] with a `schemaPath` property to notify overrides that call `super`
   *       where a schema was written for import.
   */
  public async onExportSchema(
    _schema: Schema
  ): Promise<void | ExportSchemaResult> {}

  /** This method is called when IModelExporter has made incremental progress based on the [[IModelExporter.progressInterval]] setting.
   * This method is `async` to make it easier to integrate with asynchronous status and health reporting services.
   * @note A subclass may override this method to report custom progress. The base implementation does nothing.
   */
  public async onProgress(): Promise<void> {}
}

/** Base class for exporting data from an iModel.
 * @note Most uses cases will not require a custom subclass of `IModelExporter`. Instead, it is more typical to subclass/customize [IModelExportHandler]($transformer).
 * ElementAspects are exported separately from element callbacks in bounded,
 * owner-scoped groups. Aspect callbacks are not guaranteed to be adjacent to
 * callbacks for their owners.
 * @see [iModel Transformation and Data Exchange]($docs/learning/transformer/index.md), [[registerHandler]], [IModelTransformer]($transformer), [IModelImporter]($transformer)
 * @beta
 */
export class IModelExporter {
  private static readonly _elementAspectOwnerBatchSize = 1000;
  /** The read-only source iModel. */
  public readonly sourceDb: IModelDb;
  /** A flag that indicates whether element GeometryStreams are loaded or not.
   * @note As an optimization, exporters that don't need geometry can set this flag to `false`. The default is `true`.
   * @note The transformer by default sets this to `false` as an optimization.
   * @note This implies the `wantBRepData` option when loading elements.
   * @see [ElementLoadProps.wantGeometry]($common)
   */
  public wantGeometry: boolean = true;
  /** A flag that indicates whether template models should be exported or not. The default is `true`.
   * @note If only exporting *instances* then template models can be skipped since they are just definitions that are cloned to create new instances.
   * @see [Model.isTemplate]($backend)
   */
  public wantTemplateModels: boolean = true;
  /** A flag that indicates whether *system* schemas should be exported or not. The default is `true` (previously false).
   * This can be set to false for the legacy default behavior, but it may cause errors during schema processing in some cases.
   * @see [[exportSchemas]]
   */
  public wantSystemSchemas: boolean = true;
  /** A flag that determines whether this IModelExporter should visit Elements or not. The default is `true`.
   * @note This flag is available as an optimization when the exporter doesn't need to visit elements, so can skip loading them.
   */
  public visitElements: boolean = true;
  /** A flag that determines whether this IModelExporter should visit Relationships or not. The default is `true`.
   * @note This flag is available as an optimization when the exporter doesn't need to visit relationships, so can skip loading them.
   */
  public visitRelationships: boolean = true;
  /** The number of entities exported before incremental progress should be reported via the [[onProgress]] callback. */
  public progressInterval: number = 1000;
  /** Tracks the current total number of entities exported. */
  private _progressCounter: number = 0;
  /** Optionally cached entity change information */
  private _sourceDbChanges?: ChangedInstanceIds;

  /**
   * Retrieve the cached entity change information.
   * @note This will only be initialized after [IModelExporter.exportChanges] is invoked or [IModelExporter.initialize] is called.
   */
  public get sourceDbChanges(): ChangedInstanceIds | undefined {
    return this._sourceDbChanges;
  }
  /** The handler called by this IModelExporter. */
  private _handler: IModelExportHandler | undefined;
  /** The handler called by this IModelExporter. */
  protected get handler(): IModelExportHandler {
    if (undefined === this._handler) {
      throw new Error("IModelExportHandler not registered");
    }

    return this._handler;
  }

  /** The set of CodeSpecs to exclude from the export. */
  private _excludedCodeSpecNames = new Set<string>();
  /** The set of specific Elements to exclude from the export. */
  private _excludedElementIds = new Set<Id64String>();
  /** The set of Categories where Elements in that Category will be excluded from transformation to the target iModel. */
  private _excludedElementCategoryIds = new Set<Id64String>();
  /** The set of classes of Elements that will be excluded (polymorphically) from transformation to the target iModel. */
  private _excludedElementClasses = new Set<typeof Element>();
  /** The set of classes of Relationships that will be excluded (polymorphically) from transformation to the target iModel. */
  private _excludedRelationshipClasses = new Set<typeof Relationship>();

  /** Exports ElementAspects for accepted owner groups. */
  private _elementAspectExportProcessor: ElementAspectExportProcessor;
  /** Coordinates accepted-owner scopes and bounded group processing. */
  private readonly _elementAspectExportCoordinator: ElementAspectExportCoordinator;
  /** The set of ElementAspect classes excluded from export. */
  private _excludedElementAspectClassFullNames = new Set<string>();
  /** Whether change traversal skips root-owned entities. */
  private _skipPropagateChangesToRootElements = false;
  private readonly _rootElementIds = new Set<Id64String>([
    IModel.rootSubjectId,
    IModel.repositoryModelId,
    IModel.dictionaryId,
    "0xe", // The reality-data-sources modelId, skipped with root propagation.
  ]);

  /** Construct a new IModelExporter
   * @param sourceDb The source IModelDb
   * @see registerHandler
   */
  public constructor(sourceDb: IModelDb) {
    this.sourceDb = sourceDb;
    this._elementAspectExportProcessor = new ElementAspectExportProcessor(
      this.sourceDb,
      {
        onExportElementMultiAspects: async (aspects) =>
          this.handler.onExportElementMultiAspects(aspects),
        onExportElementUniqueAspect: async (aspect, isUpdate) =>
          this.handler.onExportElementUniqueAspect(aspect, isUpdate),
        shouldExportElementAspect: async (aspect) =>
          this.handler.shouldExportElementAspect(aspect),
        shouldExportElement: async (elementId) =>
          this.shouldExportElementForAspect(elementId),
        trackProgress: async () => this.trackProgress(),
      }
    );
    this._elementAspectExportCoordinator = new ElementAspectExportCoordinator(
      IModelExporter._elementAspectOwnerBatchSize,
      () => this._excludedElementAspectClassFullNames,
      async (elementIds) =>
        this._elementAspectExportProcessor.exportAllElementAspects(elementIds)
    );
    registerElementAspectExportCoordinator(
      this,
      this._elementAspectExportCoordinator
    );
  }

  /**
   * Initialize prerequisites of exporting. This is implicitly done by any `export*` calls that need initialization
   * which is currently just `exportChanges`.
   * Prefer to not call this explicitly (e.g. just call [[IModelExporter.exportChanges]])
   * @note that if you do call this explicitly, you must do so with the same options that
   * you pass to [[IModelExporter.exportChanges]]
   */
  public async initialize(options: ExporterInitOptions): Promise<void> {
    if (!this.sourceDb.isBriefcaseDb() || this._sourceDbChanges) return;

    this._sourceDbChanges = await ChangedInstanceIds.initialize({
      iModel: this.sourceDb,
      ...options,
    });
    if (this._sourceDbChanges === undefined) return;

    this._elementAspectExportProcessor.setAspectChanges(
      this._sourceDbChanges.aspect
    );
  }

  /** Register the handler that will be called by IModelExporter. */
  public registerHandler(handler: IModelExportHandler): void {
    this._handler = handler;
  }

  /** Add a rule to exclude a CodeSpec */
  public excludeCodeSpec(codeSpecName: string): void {
    this._excludedCodeSpecNames.add(codeSpecName);
  }

  /** Add a rule to exclude a specific Element. */
  public excludeElement(elementId: Id64String): void {
    this._excludedElementIds.add(elementId);
  }

  /** Add a rule to exclude all Elements in a specified Category. */
  public excludeElementsInCategory(categoryId: Id64String): void {
    this._excludedElementCategoryIds.add(categoryId);
  }

  /** Add a rule to exclude all Elements of a specified class. */
  public excludeElementClass(classFullName: string): void {
    this._excludedElementClasses.add(
      this.sourceDb.getJsClass<typeof Element>(classFullName)
    );
  }

  /** Add a rule to exclude all ElementAspects of a specified class. */
  public excludeElementAspectClass(classFullName: string): void {
    this._excludedElementAspectClassFullNames.add(classFullName);
    this._elementAspectExportProcessor.excludeElementAspectClass(classFullName);
  }

  /** Add a rule to exclude all Relationships of a specified class. */
  public excludeRelationshipClass(classFullName: string): void {
    this._excludedRelationshipClasses.add(
      this.sourceDb.getJsClass<typeof Relationship>(classFullName)
    );
  }

  /** Export all entity instance types from the source iModel.
   * @note [[exportSchemas]] must be called separately.
   */
  public async exportAll(): Promise<void> {
    await this.initialize({});
    this._elementAspectExportCoordinator.clearOwnerExportDecisions();
    this._elementAspectExportProcessor.setAspectChanges(
      this._sourceDbChanges?.aspect
    );

    await this.exportCodeSpecs();
    await this.exportFonts();
    await this._elementAspectExportCoordinator.run(async () =>
      this.exportModel(IModel.repositoryModelId)
    );
    await this.exportRelationships(ElementRefersToElements.classFullName);
  }

  /** Export changes from the source iModel.
   * Inserts, updates, and deletes are determined by inspecting the changeset(s).
   * @throws [[ITwinError]] with scope `@itwin/imodel-transformer` and key `no-changesets` if the source iModel has no changesets and no custom changes. Call [[exportAll]] to export all content.
   * @note To form a range of versions to process, set `startChangesetId` for the start (inclusive) of the desired
   *       range and open the source iModel as of the end (inclusive) of the desired range.
   * @note the changedInstanceIds are just for this call to exportChanges, so you must continue to pass it in
   *       for consecutive calls
   */
  public async exportChanges(args?: ExportChangesOptions): Promise<void> {
    if (!this.sourceDb.isBriefcaseDb())
      throw new IModelError(
        IModelStatus.BadRequest,
        "Must be a briefcase to export changes"
      );

    let initOpts: ExporterInitOptions = args ?? {};
    const hasExplicitChangeSource =
      "csFileProps" in initOpts ||
      "changedInstanceIds" in initOpts ||
      "changesetRanges" in initOpts ||
      "startChangeset" in initOpts;
    const currentChangesetId = this.sourceDb.changeset.id;

    if (!hasExplicitChangeSource && currentChangesetId !== "") {
      initOpts = {
        ...initOpts,
        startChangeset: { id: currentChangesetId },
      };
    }

    await this.initialize(initOpts);

    if (currentChangesetId === "" && !this.sourceDbChanges?.hasChanges) {
      ITwinError.throwError({
        iTwinErrorId: {
          scope: "@itwin/imodel-transformer",
          key: "no-changesets",
        },
        message:
          "Cannot export changes because the source iModel has no changesets or custom changes. Call exportAll() to export all content.",
      });
    }

    this._elementAspectExportCoordinator.clearOwnerExportDecisions();
    this._skipPropagateChangesToRootElements =
      initOpts.skipPropagateChangesToRootElements ?? false;
    // _sourceDbChanges are initialized in this.initialize
    nodeAssert(
      this._sourceDbChanges !== undefined,
      "sourceDbChanges must be initialized."
    );

    await this.exportCodeSpecs();
    await this.exportFonts();
    await this._elementAspectExportCoordinator.run(async () => {
      if (initOpts.skipPropagateChangesToRootElements) {
        // The root Subject is in the RepositoryModel. Traverse its children
        // separately, then export other top-level repository elements while
        // excluding the root so no element is visited twice.
        await this.exportChildElements(IModel.rootSubjectId);
        await this.exportModelContents(
          IModel.repositoryModelId,
          Element.classFullName,
          true
        );
        await this.exportSubModels(IModel.repositoryModelId);
      } else {
        await this.exportModel(IModel.repositoryModelId);
      }
    });
    await this.exportAllAspects(
      await this.getChangedElementIdsForAspectExport(false)
    );
    await this.exportRelationships(ElementRefersToElements.classFullName);

    // handle deletes
    if (this.visitElements) {
      // must delete models first since they have a constraint on the submodeling element which may also be deleted
      for (const modelId of this._sourceDbChanges.model.deleteIds) {
        await this.handler.onDeleteModel(modelId);
      }
      for (const elementId of this._sourceDbChanges.element.deleteIds) {
        // We don't know how the handler wants to handle deletions, and we don't have enough information
        // to know if deleted entities were related, so when processing changes, ignore errors from deletion.
        // Technically, to keep the ignored error scope small, we ignore only the error of looking up a missing element,
        // that approach works at least for the IModelTransformer.
        // In the future, the handler may be responsible for doing the work of finding out which elements were cascade deleted,
        // and returning them for the exporter to use to avoid double-deleting with error ignoring
        try {
          await this.handler.onDeleteElement(elementId);
        } catch (err: unknown) {
          const isMissingErr =
            err instanceof IModelError &&
            err.errorNumber === IModelStatus.NotFound;
          if (!isMissingErr) throw err;
        }
      }
    }

    if (this.visitRelationships) {
      for (const relInstanceId of this._sourceDbChanges.relationship
        .deleteIds) {
        await this.handler.onDeleteRelationship(relInstanceId);
      }
    }

    // Enable consecutive exportChanges runs without the need to re-instantiate the exporter.
    // You can counteract the obvious impact of losing this expensive data by always calling
    // exportChanges with the [[ExportChangesOptions.changedInstanceIds]] option set to
    // whatever you want
    if (this._resetChangeDataOnExport) {
      this._sourceDbChanges = undefined;
      this._elementAspectExportProcessor.setAspectChanges(undefined);
    }
  }

  private _resetChangeDataOnExport = true;

  /** Export schemas from the source iModel.
   * @note This must be called separately from [[exportAll]] or [[exportChanges]].
   */
  public async exportSchemas(): Promise<void> {
    const sql = `
      SELECT s.Name, s.VersionMajor, s.VersionWrite, s.VersionMinor
      FROM ECDbMeta.ECSchemaDef s
      ${
        this.wantSystemSchemas
          ? ""
          : `
      WHERE ECInstanceId >= (SELECT ECInstanceId FROM ECDbMeta.ECSchemaDef WHERE Name='BisCore')
      `
      }
      ORDER BY ECInstanceId
    `;
    const schemaKeysToExport: SchemaKey[] = [];
    for await (const row of this.sourceDb.createQueryReader(sql, undefined, {
      usePrimaryConn: true,
    })) {
      const schemaName = row[0];
      const versionMajor = row[1];
      const versionWrite = row[2];
      const versionMinor = row[3];
      const schemaKey = new SchemaKey(
        schemaName,
        new ECVersion(versionMajor, versionWrite, versionMinor)
      );
      if (await this.handler.shouldExportSchema(schemaKey)) {
        schemaKeysToExport.push(schemaKey);
      }
    }
    if (schemaKeysToExport.length === 0) return;

    await Promise.all(
      schemaKeysToExport.map(async (schemaKey) => {
        const schema = await this.sourceDb.schemaContext.getSchema(schemaKey);
        if (!schema) {
          throw new Error(`Failed to load schema: ${schemaKey.name}`);
        }
        Logger.logTrace(loggerCategory, `exportSchema(${schemaKey.name})`);
        return this.handler.onExportSchema(schema);
      })
    );
  }

  /** For logging, indicate the change type if known. */
  private getChangeOpSuffix(isUpdate: boolean | undefined): string {
    return isUpdate ? " UPDATE" : undefined === isUpdate ? "" : " INSERT";
  }

  /** Export all CodeSpecs from the source iModel.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportCodeSpecs(): Promise<void> {
    Logger.logTrace(loggerCategory, "exportCodeSpecs()");
    const sql = "SELECT Name FROM BisCore:CodeSpec ORDER BY ECInstanceId";
    for await (const row of this.sourceDb.createQueryReader(sql, undefined, {
      usePrimaryConn: true,
    })) {
      await this.exportCodeSpecByName(row[0]);
    }
  }

  /** Export a single CodeSpec from the source iModel.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportCodeSpecByName(codeSpecName: string): Promise<void> {
    const codeSpec: CodeSpec = this.sourceDb.codeSpecs.getByName(codeSpecName);
    let isUpdate: boolean | undefined;
    if (undefined !== this._sourceDbChanges) {
      // is changeset information available?
      if (this._sourceDbChanges.codeSpec.insertIds.has(codeSpec.id)) {
        isUpdate = false;
      } else if (this._sourceDbChanges.codeSpec.updateIds.has(codeSpec.id)) {
        isUpdate = true;
      } else {
        return; // not in changeset, don't export
      }
    }
    // passed changeset test, now apply standard exclusion rules
    if (this._excludedCodeSpecNames.has(codeSpec.name)) {
      Logger.logInfo(loggerCategory, `Excluding CodeSpec: ${codeSpec.name}`);
      return;
    }
    // CodeSpec has passed standard exclusion rules, now give handler a chance to accept/reject export
    if (await this.handler.shouldExportCodeSpec(codeSpec)) {
      Logger.logTrace(
        loggerCategory,
        `exportCodeSpec(${codeSpecName})${this.getChangeOpSuffix(isUpdate)}`
      );
      await this.handler.onExportCodeSpec(codeSpec, isUpdate);
      return this.trackProgress();
    }
  }

  /** Export a single CodeSpec from the source iModel.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportCodeSpecById(codeSpecId: Id64String): Promise<void> {
    const codeSpec: CodeSpec = this.sourceDb.codeSpecs.getById(codeSpecId);
    return this.exportCodeSpecByName(codeSpec.name);
  }

  /** Export all fonts from the source iModel.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportFonts(): Promise<void> {
    Logger.logTrace(loggerCategory, "exportFonts()");
    for (const font of this.sourceDb.fonts.queryMappedFamilies()) {
      await this.exportFontByFontProps(font);
    }
  }

  /** Export a single font from the source iModel.
   * @note multiple fonts can have the same font name, if a font with a specific type is needed use exportFontByFontFamilyDescriptor.
   * If not this will only export the first font with this type in the db.
   */
  public async exportFontByName(fontName: string): Promise<void> {
    Logger.logTrace(loggerCategory, `exportFontByName(${fontName})`);
    const fontId: FontId | undefined = this.sourceDb.fonts.findId({
      name: fontName,
    });
    if (undefined !== fontId) {
      await this.exportFontByNumber(fontId);
    }
  }

  /** Export a single font from the source iModel.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportFontByFontProps(fontProps: FontProps): Promise<void> {
    Logger.logTrace(
      loggerCategory,
      `exportFontByFamily(${fontProps.name}, ${fontProps.type})`
    );
    await this.handler.onExportFont(fontProps, true);
    return this.trackProgress();
  }

  /** Export a single font from the source iModel.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportFontByFontFamilyDescriptor(
    fontFamily: FontFamilyDescriptor
  ): Promise<void> {
    Logger.logTrace(
      loggerCategory,
      `exportFontByFamilyDescriptor(${fontFamily.name}, ${fontFamily.type})`
    );
    const fontId: FontId | undefined =
      await this.sourceDb.fonts.acquireId(fontFamily);
    if (undefined !== fontId) {
      await this.exportFontByFontProps({ ...fontFamily, id: fontId });
    }
  }

  /** Export a single font from the source iModel.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportFontByNumber(fontNumber: number): Promise<void> {
    /** sourceDbChanges now works by using TS ChangesetECAdaptor which doesn't pick up changes to fonts since fonts is not an ec table.
     * So lets always export fonts for the time being by always setting isUpdate = true.
     * It is very rare and even problematic for the font table to reach a large size, so it is not a bottleneck in transforming changes.
     * See https://github.com/iTwin/imodel-transformer/pull/135 for removed code.
     */
    Logger.logTrace(loggerCategory, `exportFontById(${fontNumber})`);
    const font: FontFamilyDescriptor | undefined =
      this.sourceDb.fonts.findDescriptor(fontNumber);
    if (undefined !== font) {
      await this.exportFontByFontFamilyDescriptor(font);
    }
  }

  /** Export the model container, contents, and sub-models from the source iModel.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportModel(modeledElementId: Id64String): Promise<void> {
    return this.runScopedElementExport(async () =>
      this.exportModelImpl(modeledElementId)
    );
  }

  private async exportModelImpl(modeledElementId: Id64String): Promise<void> {
    const model: Model = this.sourceDb.models.getModel(modeledElementId);
    if (model.isTemplate && !this.wantTemplateModels) {
      return;
    }
    const modeledElement: Element = this.sourceDb.elements.getElement({
      id: modeledElementId,
      wantGeometry: this.wantGeometry,
      wantBRepData: this.wantGeometry,
    });
    Logger.logTrace(loggerCategory, `exportModel(${modeledElementId})`);
    if (await this.shouldExportElement(modeledElement)) {
      await this.exportModelContainer(model);
      if (this.visitElements) {
        await this.exportModelContents(modeledElementId);
      }
      await this.exportSubModels(modeledElementId);
    }
  }

  /** Export the model (the container only) from the source iModel. */
  private async exportModelContainer(model: Model): Promise<void> {
    let isUpdate: boolean | undefined;
    if (undefined !== this._sourceDbChanges) {
      // is changeset information available?
      if (this._sourceDbChanges.model.insertIds.has(model.id)) {
        isUpdate = false;
      } else if (this._sourceDbChanges.model.updateIds.has(model.id)) {
        isUpdate = true;
      } else {
        return; // not in changeset, don't export
      }
    }
    await this.handler.onExportModel(model, isUpdate);
    return this.trackProgress();
  }

  private _yieldManager = new YieldManager();

  /** Export the model contents.
   * @param modelId The only required parameter
   * @param elementClassFullName Can be optionally specified if the goal is to export a subset of the model contents
   * @param skipRootSubject Decides whether or not to export the root Subject. It is normally left undefined except for internal implementation purposes.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportModelContents(
    modelId: Id64String,
    elementClassFullName: string = Element.classFullName,
    skipRootSubject?: boolean
  ): Promise<void> {
    return this.runScopedElementExport(async () =>
      this.exportModelContentsImpl(
        modelId,
        elementClassFullName,
        skipRootSubject
      )
    );
  }

  private async exportModelContentsImpl(
    modelId: Id64String,
    elementClassFullName: string,
    skipRootSubject?: boolean
  ): Promise<void> {
    if (skipRootSubject) {
      // NOTE: IModelTransformer.processAll should skip the root Subject since it is specific to the individual iModel and is not part of the changes that need to be synchronized
      // NOTE: IModelExporter.exportAll should not skip the root Subject since the goal is to export everything
      assert(modelId === IModel.repositoryModelId); // flag is only relevant when processing the RepositoryModel
    }
    if (!this.visitElements) {
      Logger.logTrace(
        loggerCategory,
        `visitElements=false, skipping exportModelContents(${modelId})`
      );
      return;
    }
    if (undefined !== this._sourceDbChanges) {
      // is changeset information available?
      if (
        !this._sourceDbChanges.model.insertIds.has(modelId) &&
        !this._sourceDbChanges.model.updateIds.has(modelId)
      ) {
        return; // this optimization assumes that the Model changes (LastMod) any time an Element in the Model changes
      }
    }
    Logger.logTrace(loggerCategory, `exportModelContents(${modelId})`);
    let sql: string;
    if (skipRootSubject) {
      sql = `SELECT ECInstanceId FROM ${elementClassFullName} WHERE Parent.Id IS NULL AND Model.Id=:modelId AND ECInstanceId!=:rootSubjectId ORDER BY ECInstanceId`;
    } else {
      sql = `SELECT ECInstanceId FROM ${elementClassFullName} WHERE Parent.Id IS NULL AND Model.Id=:modelId ORDER BY ECInstanceId`;
    }
    const params = new QueryBinder().bindId("modelId", modelId);
    if (skipRootSubject) {
      params.bindId("rootSubjectId", IModel.rootSubjectId);
    }
    for await (const row of this.sourceDb.createQueryReader(sql, params, {
      usePrimaryConn: true,
    })) {
      await this.exportElement(row.id);
      await this._yieldManager.allowYield();
    }
  }

  /** Export the sub-models directly below the specified model.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportSubModels(parentModelId: Id64String): Promise<void> {
    return this.runScopedElementExport(async () =>
      this.exportSubModelsImpl(parentModelId)
    );
  }

  private async exportSubModelsImpl(parentModelId: Id64String): Promise<void> {
    Logger.logTrace(loggerCategory, `exportSubModels(${parentModelId})`);
    const definitionModelIds: Id64String[] = [];
    const otherModelIds: Id64String[] = [];
    const sql = `SELECT ECInstanceId FROM ${Model.classFullName} WHERE ParentModel.Id=:parentModelId ORDER BY ECInstanceId`;
    const params = new QueryBinder().bindId("parentModelId", parentModelId);
    for await (const row of this.sourceDb.createQueryReader(sql, params, {
      usePrimaryConn: true,
    })) {
      const modelId: Id64String = row.id;
      const model: Model = this.sourceDb.models.getModel(modelId);
      if (model instanceof DefinitionModel) {
        definitionModelIds.push(modelId);
      } else {
        otherModelIds.push(modelId);
      }
    }
    // export DefinitionModels before other types of Models
    for (const definitionModelId of definitionModelIds) {
      await this.exportModel(definitionModelId);
    }
    for (const otherModelId of otherModelIds) {
      await this.exportModel(otherModelId);
    }
  }

  /** Returns true if the specified element should be exported.
   * This considers the standard IModelExporter exclusion rules plus calls [IModelExportHandler.shouldExportElement]($transformer) for any custom exclusion rules.
   * @note This method is called from within [[exportChanges]] and [[exportAll]], so usually does not need to be called directly.
   */
  public async shouldExportElement(element: Element): Promise<boolean> {
    let shouldExport = true;
    if (this._excludedElementIds.has(element.id)) {
      Logger.logInfo(loggerCategory, `Excluded element ${element.id} by Id`);
      shouldExport = false;
    }
    if (shouldExport && element instanceof GeometricElement) {
      if (this._excludedElementCategoryIds.has(element.category)) {
        Logger.logInfo(
          loggerCategory,
          `Excluded element ${element.id} by Category`
        );
        shouldExport = false;
      }
    }
    if (
      shouldExport &&
      !this.wantTemplateModels &&
      element instanceof RecipeDefinitionElement
    ) {
      Logger.logInfo(
        loggerCategory,
        `Excluded RecipeDefinitionElement ${element.id} because wantTemplate=false`
      );
      shouldExport = false;
    }
    if (shouldExport) {
      for (const excludedElementClass of this._excludedElementClasses) {
        if (element instanceof excludedElementClass) {
          Logger.logInfo(
            loggerCategory,
            `Excluded element ${element.id} by class: ${excludedElementClass.classFullName}`
          );
          shouldExport = false;
          break;
        }
      }
    }
    if (shouldExport) {
      // element has passed standard exclusion rules, now give handler a chance to accept/reject
      shouldExport = await this.handler.shouldExportElement(element);
    }
    if (shouldExport) {
      this._elementAspectExportCoordinator.recordAcceptedOwnerDecision(
        element.id
      );
    }
    return shouldExport;
  }

  /** Export the specified element and its child elements (if applicable).
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   * @note ElementAspects are exported separately in owner-scoped groups, so their callbacks are not guaranteed to follow this element callback.
   */
  public async exportElement(elementId: Id64String): Promise<void> {
    return this.runScopedElementExport(async () =>
      this.exportElementImpl(elementId)
    );
  }

  private async exportElementImpl(elementId: Id64String): Promise<void> {
    if (!this.visitElements) {
      Logger.logTrace(
        loggerCategory,
        `visitElements=false, skipping exportElement(${elementId})`
      );
      return;
    }

    // Return early if the elementId is already in the excludedElementIds, that way we don't need to load the element from the db.
    if (this._excludedElementIds.has(elementId)) {
      Logger.logInfo(loggerCategory, `Excluded element ${elementId} by Id`);
      await this.handler.onSkipElement(elementId);
      return;
    }

    // are we processing changes?
    const isUpdate = this._sourceDbChanges?.element.insertIds.has(elementId)
      ? false
      : this._sourceDbChanges?.element.updateIds.has(elementId)
        ? true
        : undefined;

    // Short-circuit: element is not in the changeset, skip its own export but still visit children
    if (undefined !== this._sourceDbChanges && undefined === isUpdate) {
      return this.exportChildElements(elementId);
    }

    const element = this.sourceDb.elements.getElement({
      id: elementId,
      wantGeometry: this.wantGeometry,
      wantBRepData: this.wantGeometry,
    });
    Logger.logTrace(
      loggerCategory,
      `exportElement(${
        element.id
      }, "${element.getDisplayLabel()}")${this.getChangeOpSuffix(isUpdate)}`
    );
    // the order and `await`ing of calls beyond here is depended upon by the IModelTransformer for a current bug workaround
    if (await this.shouldExportElement(element)) {
      await this.handler.preExportElement(element);
      await this.handler.onExportElement(element, isUpdate);
      await this.trackProgress();
      await this._elementAspectExportCoordinator.addAcceptedOwner(elementId);
      return this.exportChildElements(elementId);
    } else {
      await this.handler.onSkipElement(element.id);
    }
  }

  /** Export the child elements of the specified element from the source iModel.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportChildElements(elementId: Id64String): Promise<void> {
    return this.runScopedElementExport(async () =>
      this.exportChildElementsImpl(elementId)
    );
  }

  private async exportChildElementsImpl(elementId: Id64String): Promise<void> {
    if (!this.visitElements) {
      Logger.logTrace(
        loggerCategory,
        `visitElements=false, skipping exportChildElements(${elementId})`
      );
      return;
    }
    const childElementIds: Id64String[] =
      this.sourceDb.elements.queryChildren(elementId);
    if (childElementIds.length > 0) {
      Logger.logTrace(loggerCategory, `exportChildElements(${elementId})`);
      for (const childElementId of childElementIds) {
        await this.exportElement(childElementId);
      }
    }
  }

  /** Exports all aspects present in the iModel.
   */
  private async exportAllAspects(
    elementIds?: ReadonlySet<Id64String>
  ): Promise<void> {
    elementIds ??= await this.getChangedElementIdsForAspectExport();
    return this._elementAspectExportCoordinator.exportOwners(
      elementIds ?? new Set<Id64String>()
    );
  }

  private async getChangedElementIdsForAspectExport(
    includeElementChanges = true
  ): Promise<ReadonlySet<Id64String> | undefined> {
    if (this._sourceDbChanges === undefined) return undefined;

    const changedElementIds = new Set<Id64String>([
      ...(includeElementChanges
        ? [
            ...this._sourceDbChanges.element.insertIds,
            ...this._sourceDbChanges.element.updateIds,
          ]
        : []),
      ...getAspectOwnerElementIds(this._sourceDbChanges),
    ]);
    if (!includeElementChanges) {
      for (const elementId of this._sourceDbChanges.element.insertIds) {
        changedElementIds.delete(elementId);
      }
      for (const elementId of this._sourceDbChanges.element.updateIds) {
        changedElementIds.delete(elementId);
      }
    }
    if (changedElementIds.size === 0) return new Set<Id64String>();

    const elementIds = new Set<Id64String>();
    for (const elementId of changedElementIds) {
      if (
        this._skipPropagateChangesToRootElements &&
        this._rootElementIds.has(elementId)
      ) {
        continue;
      }
      if (
        this.sourceDb.elements.tryGetElement(elementId) !== undefined &&
        (await this.shouldExportElementHierarchyForAspect(elementId))
      ) {
        elementIds.add(elementId);
      }
    }
    return elementIds;
  }

  private async shouldExportElementHierarchyForAspect(
    elementId: Id64String
  ): Promise<boolean> {
    let element = this.sourceDb.elements.tryGetElement(elementId);
    while (element !== undefined) {
      if (!(await this.shouldExportElementForAspect(element.id))) return false;
      if (!(await this.shouldExportModelForAspect(element.model))) {
        return false;
      }
      const parentId = element.parent?.id;
      if (
        parentId === undefined ||
        (this._skipPropagateChangesToRootElements &&
          parentId === IModel.rootSubjectId)
      ) {
        return true;
      }
      element = this.sourceDb.elements.tryGetElement(parentId);
    }
    return false;
  }

  private async shouldExportModelForAspect(
    modelId: Id64String
  ): Promise<boolean> {
    const model = this.sourceDb.models.getModel(modelId);
    if (model.isTemplate && !this.wantTemplateModels) return false;
    if (
      model.id !== IModel.repositoryModelId &&
      model.id !== IModel.dictionaryId &&
      model.id !== "0xe" &&
      !(await this.shouldExportElementForAspect(model.id))
    ) {
      return false;
    }
    if (model.parentModel === undefined || model.parentModel === model.id) {
      return true;
    }
    return this.shouldExportModelForAspect(model.parentModel);
  }

  private async runScopedElementExport(
    exportElements: () => Promise<void>
  ): Promise<void> {
    await this._elementAspectExportCoordinator.run(exportElements);
  }

  /** Apply the element export filter when deciding whether to process an aspect owner. @internal */
  private async shouldExportElementForAspect(
    elementId: Id64String
  ): Promise<boolean> {
    if (!this.visitElements) return false;

    const cachedDecision =
      this._elementAspectExportCoordinator.getOwnerExportDecision(elementId);
    if (cachedDecision !== undefined) return cachedDecision;

    const element = this.sourceDb.elements.getElement({
      id: elementId,
      wantGeometry: false,
      wantBRepData: false,
    });
    return this.shouldExportElement(element);
  }

  /** Exports all relationships that subclass from the specified base class.
   * @note This method is called from [[exportChanges]] and [[exportAll]], so it only needs to be called directly when exporting a subset of an iModel.
   */
  public async exportRelationships(
    baseRelClassFullName: string
  ): Promise<void> {
    if (!this.visitRelationships) {
      Logger.logTrace(
        loggerCategory,
        "visitRelationships=false, skipping exportRelationships()"
      );
      return;
    }
    Logger.logTrace(
      loggerCategory,
      `exportRelationships(${baseRelClassFullName})`
    );
    const sql = `SELECT r.ECInstanceId, ec_className(r.ECClassId, 's.c') as className FROM ${baseRelClassFullName} r
                  JOIN bis.Element s ON s.ECInstanceId = r.SourceECInstanceId
                  JOIN bis.Element t ON t.ECInstanceId = r.TargetECInstanceId
                  WHERE s.ECInstanceId IS NOT NULL AND t.ECInstanceId IS NOT NULL`;
    for await (const row of this.sourceDb.createQueryReader(sql, undefined, {
      usePrimaryConn: true,
    })) {
      const relationshipId = row.id;
      const relationshipClass = row.className;
      await this.exportRelationship(relationshipClass, relationshipId); // must call exportRelationship using the actual classFullName, not baseRelClassFullName
      await this._yieldManager.allowYield();
    }
  }

  /** Export a relationship from the source iModel. */
  public async exportRelationship(
    relClassFullName: string,
    relInstanceId: Id64String
  ): Promise<void> {
    if (!this.visitRelationships) {
      Logger.logTrace(
        loggerCategory,
        `visitRelationships=false, skipping exportRelationship(${relClassFullName}, ${relInstanceId})`
      );
      return;
    }
    let isUpdate: boolean | undefined;
    if (undefined !== this._sourceDbChanges) {
      // is changeset information available?
      if (this._sourceDbChanges.relationship.insertIds.has(relInstanceId)) {
        isUpdate = false;
      } else if (
        this._sourceDbChanges.relationship.updateIds.has(relInstanceId)
      ) {
        isUpdate = true;
      } else {
        return; // not in changeset, don't export
      }
    }
    // passed changeset test, now apply standard exclusion rules
    Logger.logTrace(
      loggerCategory,
      `exportRelationship(${relClassFullName}, ${relInstanceId})`
    );
    const relationship: Relationship = this.sourceDb.relationships.getInstance(
      relClassFullName,
      relInstanceId
    );
    for (const excludedRelationshipClass of this._excludedRelationshipClasses) {
      if (relationship instanceof excludedRelationshipClass) {
        Logger.logInfo(
          loggerCategory,
          `Excluded relationship by class: ${excludedRelationshipClass.classFullName}`
        );
        return;
      }
    }
    // relationship has passed standard exclusion rules, now give handler a chance to accept/reject export
    if (await this.handler.shouldExportRelationship(relationship)) {
      await this.handler.onExportRelationship(relationship, isUpdate);
      await this.trackProgress();
    }
  }

  /** Tracks incremental progress */
  private async trackProgress(): Promise<void> {
    this._progressCounter++;
    if (0 === this._progressCounter % this.progressInterval) {
      return this.handler.onProgress();
    }
  }
}
